
# see http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# see https://github.com/spring-cloud/spring-cloud-config/blob/d9113a417dccff271744be3a4039e270b0cebd76/docs/src/main/asciidoc/spring-cloud-config.adoc#quick-start
# see https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc
# see https://github.com/spring-cloud/spring-cloud-netflix/blob/8fb89b25d955fe175410853cea3b09333ef32d74/docs/src/main/asciidoc/spring-cloud-netflix.adoc
# see: https://github.com/Netflix

info:
  title: ${project.name}
  git:
    commitID: ${git.commit.id}
    commitTime: ${git.commit.time}

# =========================
# HEALTH INDICATORS (previously health.*)
# =========================
management:
  context-path: /admin # Management endpoint context-path. For instance `/actuator`
  security:
    enabled: false
  health:
    defaults:
      enabled: true # Enable default health indicators
    db:
      enabled: false # Enable database health check
    diskspace:
      enabled: false # Enable disk space health check
      path: / # Path used to compute the available disk space
      threshold: 0 # Minimum disk space that should be available, in bytes
    elasticsearch:
      enabled: false # Enable elasticsearch health check
      indices: # Comma-separated index names
      response-timeout: 100 # The time, in milliseconds, to wait for a response from the cluster
    jms:
      enabled: false # Enable JMS health check
    mail:
      enabled: false # Enable Mail health check
    mongo:
      enabled: false # Enable MongoDB health check
    rabbit:
      enabled: false # Enable RabbitMQ health check
    redis:
      enabled: false # Enable Redis health check
    solr:
      enabled: false # Enable Solr health check
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP # Comma-separated list of health statuses in order of severity
health:
  config:
    enabled: false # Turn on/off health indicator for config clients.

# =========================
# ACTUATOR PROPERTIES
# =========================
# ENDPOINTS (AbstractEndpoint subclasses)
endpoints:
  enabled: true
  sensitive: false
  actuator:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: false
    keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services # Keys that should be sanitized. Keys can be simple strings that the property ends with or regex expressions.
  docs:
    enabled: true
    sensitive: false
    curies:
      enabled: false
  dump:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
    keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services # Keys that should be sanitized. Keys can be simple strings that the property ends with or regex expressions.
  endpoints:
    flyway:
      enabled: true
      sensitive: false
  health:
    enabled: true
    sensitive: false
    time-to-live: 10000
  heapdump:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  jolokia:
    enabled: true
    sensitive: false
  liquibase:
    enabled: true
    sensitive: false
  logfile:
    enabled: true
    sensitive: false
  mappings:
      enabled: true
      sensitive: false
  metrics:
    enabled: true
    sensitive: false
    filter:
      enabled: true
  shutdown:
    enabled: true
    sensitive: false
  trace:
    enabled: true
    sensitive: false

# =========================
# PROFILE LOCAL
# =========================
spring:
  profiles: local, integration-test

      
# ----------------------------------------
# FEIGN
# ----------------------------------------
feign:
  histrix:
    enabled: false
  compression:
    request:
      enabled: true
    response:
      enabled: true

# ----------------------------------------
# HYSTRIX
# ----------------------------------------
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
            interruptOnTimeout: true
          semaphore:
            maxConcurrentRequests: 10
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
        forceOpen: false
        forceClosed: false
      metrics:
        rollingStats:
        timeInMilliseconds: 10000
        numBuckets: 10
      rollingPercentile:
        enabled: true
        timeInMilliseconds: 60000
        numBuckets: 6
        bucketSize: 100
      healthSnapshot:
        intervalInMilliseconds: 500

# =========================
# Logging configuration
# =========================
logging:
  level:
    org.springframework: WARN
    com.sample: DEBUG
  pattern:
    console: '%highlight{%-5p|%d{ISO8601}{GMT}|trace=%X{X-B3-TraceId},span=%X{X-B3-SpanId}|%c{1}|%m%ex%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=blue bold, DEBUG=green bold, TRACE=blue}'
    file: '%-5p|%d{ISO8601}{GMT}|trace=%X{X-B3-TraceId},span=%X{X-B3-SpanId}|%c{1}|%m%ex%n'
  config: classpath:log4j2-spring.xml

# =========================
# Swagger configuration
# =========================
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
      host: localhost:8081
